
services:
  database_mysql:
    image: "mysql:latest"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r
      MYSQL_DATABASE: my_database
    networks:
      - express-mysql
    ports:
      - "3307:3306"
      - "33070:33060"
    expose:
      - 3306
      - 33060
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 30s
      timeout: 10s
      retries: 5
  api:
      build: .
      networks:
        - express-mysql
      depends_on:
        database_mysql:
          condition: service_healthy
      ports:
        - "3001:3000"
networks:
  express-mysql: {}
